# This is a basic workflow to help you get started with Actions

name: Jupyter

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          cache: pip
          python-version: '3.7'
          
      # Runs a set of commands using the runners shell
      - name: Install Dependencies #Installing dependencies for Jupiter
        run: pip install -r requirements.txt
        
      - name: Exeute Notebook # Performing a Jupyter Notebook
        run: jupyter-nbconvert --execute Domashka_2.ipynb --to html
        
      - name: Upload a Build Artifact # Uploading the output of a notebook (task artifact) to an html file
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Artifact
          path:  Domashka_2.html
